name: Generate Snake Animations

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git config --global user.name 'Sm-bello'
          git config --global user.email 'youremail@example.com'

      - name: Generate Snake Animation
        uses: Platane/snk@v1.1.0
        id: snake
        with:
          github_user: 'Sm-bello'
          svg_out: 'github/snake'

      - name: Commit and Push Snake Animation
        run: |
          git add github/snake/*.svg
          git commit -m 'Update snake animations' || echo 'No changes to commit'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
